### ISSUE TITLE
Plugins and loads_fn/dumps_fn

### ISSUE THREAD

**Issue by ahopkins** [argaen/aiocache#381] opened 2018-01-31 13:11 UTC
I have a setup similar to your example using the two plugins you have.

    d = {
        'cache': "aiocache.RedisCache",
        'serializer': {
            'class': environ.get('AIOCACHE_SERIALIZER')
        },
        'plugins': [
            {'class': "aiocache.plugins.HitMissRatioPlugin"},
            {'class': "aiocache.plugins.TimingPlugin"}
        ],
    }

I wanted to bypass the serializer for one routine that I have that I have (because I wanted to leverage the `increment` feature which does not seem to work with serialized data). 

I added `loads_fn` and `dumps_fn`, but this caused the below exception. When removing the plugins, it worked as expected.

      File "/usr/src/app/lib/cache/__init__.py", line 40, in get
        value = await self.cache.get(key, *args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 58, in _enabled
        return await func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 43, in _timeout
        return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
      File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
        return fut.result()
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 77, in _plugins
        self, *args, took=end - start, ret=ret, **kwargs)
    TypeError: post_get() got an unexpected keyword argument 'loads_fn'

**Comment by argaen** [comment] 2018-01-31 18:24
Can you put here a snippet to reproduce the error? With I'll be able to
debug your problem and help :)

Also I don't understand what you mean by "I added loads_fn and dumps_fn"

**Comment by ahopkins** [comment] 2018-02-01 10:35
Let's say I have something like this (using the Message Pack serializer #362).

```python
key = "SOMESTRING"
value = 120
await cache.set(key, value, )
```
Checking the redis value returns this:

    0.0.0.0:6379> get "SOMETHING"
    "x"

If I try to decode it, it works as expected.

    >>> import msgpack
    >>> msgpack.loads(b'x')
    120

If I try to increment, it breaks down. Which, sort of is fine because I am not actually storing an integer in Redis.

```python
to_increment = 10
await cache.increment(key, to_increment)
```

      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 58, in _enabled
        return await func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 43, in _timeout
        return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
      File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
        return fut.result()
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 71, in _plugins
        ret = await func(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 365, in increment
        ret = await self._increment(ns_key, delta, _conn=_conn)
    queue_1  |   File "/usr/local/lib/python3.6/site-packages/aiocache/backends/redis.py", line 24, in     return await func(self, *args, _conn=_conn, **kwargs)
    queue_1  |   File "/usr/local/lib/python3.6/site-packages/aiocache/backends/redis.py", line 159, t
        raise TypeError("Value is not an integer") from None
    TypeError: Value is not an integer

So, I need a way to **NOT** serialize using Message Pack for this one operation where I knew I will need to make use of `increment`.

Therefore, I changed my code to something like this, so that I am explicitly telling `aiocache` to ignore Message Pack.

```python
key = "SOMESTRING"
value = 120
await cache.set(key, value, dumps_fn=lambda x: x )
```

Redis now is storing my integers as integers and not serialized versions. However, if I try to increment, I get the exception that I displayed above.

      File "/usr/src/app/lib/cache/__init__.py", line 40, in get
        value = await self.cache.get(key, *args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 58, in _enabled
        return await func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 43, in _timeout
        return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
      File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
        return fut.result()
      File "/usr/local/lib/python3.6/site-packages/aiocache/base.py", line 77, in _plugins
        self, *args, took=end - start, ret=ret, **kwargs)
    TypeError: post_get() got an unexpected keyword argument 'loads_fn'

If I take out the plugins:

    d = {
        'cache': "aiocache.RedisCache",
        'serializer': {
            # 'class': "aiocache.serializers.MessagePackSerializer"
            'class': environ.get('AIOCACHE_SERIALIZER')
        },
        # 'plugins': [
        #     {'class': "aiocache.plugins.HitMissRatioPlugin"},
        #     {'class': "aiocache.plugins.TimingPlugin"}
        # ],
    }

Everything works as expected.

**Comment by argaen** [comment] 2018-04-03 21:03
Hi @ahopkins, I can't reproduce. This is the snippet I used according to what you explained:
```
import asyncio
import aiocache
from aiocache import plugins


cache = aiocache.RedisCache(
    serializer=aiocache.serializers.MsgPackSerializer(),
    plugins=[
        plugins.HitMissRatioPlugin(),
        plugins.TimingPlugin()
    ]
)


async def test():
    await cache.set('key', 1, dumps_fn=lambda x: x)
    await cache.increment('key')


asyncio.get_event_loop().run_until_complete(test())
```
and the result:
```
127.0.0.1:6379> get key
"2"
```

**Comment by argaen** [comment] 2018-10-02 15:47
Closing this issue, feel free to reopen with more info if you still facing it

**Closed by argaen** 2018-10-02 15:47 UTC

**Comment by ahopkins** [comment] 2018-10-02 16:37
Thanks. I think I am all set.
